-- Generated by hyprmoncfg

hl.monitor({
  output = "desc:AU Optronics 0x208D",
  mode = "1920x1080@60.05",
  position = "0x600",
  scale = 1,
  sdr_min_luminance = 0.2,
  sdr_max_luminance = 100,
})
