add_newline = true
command_timeout = 2000

format = """$env_var$os$username$hostname$kubernetes$docker_context$directory$git_branch$git_status$python$golang$c$lua
$character
"""

[character]
success_symbol = "[╰⎯](#d4be98)"
error_symbol = "[╰⎯](#ea6962)"

[env_var]
symbol = "╭╴"
variable = 'SHELL'
format = "$symbol"
disabled = false

[os]
format = '[$symbol](#7daea3)'
disabled = false

[os.symbols]
Windows = ''
Arch = ''
Fedora = ''
Ubuntu = ''
Macos = '󰀵'
Unknown = '󰠥'

[username]
style_user = '#d3869b bold'
style_root = '#ea6962 bold'
format = '[//](#3c3836) [$user]($style) '
disabled = false
show_always = true

[hostname]
ssh_only = false
format = '[//](#3c3836) [$hostname](#89b482 bold) '
disabled = false

[directory]
truncation_length = 0
truncation_symbol = '…/'
home_symbol = '~'
read_only = '  '
format = '[//](#3c3836) [$path]($style)[$read_only]($read_only_style) '
style = '#7daea3'
read_only_style = '#ea6962'

[git_branch]
symbol = ' '
format = '[//](#3c3836) [$symbol\[$branch\]]($style) '
style = '#a9b665'

[git_status]
disabled = true
format = '[ $all_status $ahead_behind]($style) '
style = '#a9b665'

conflicted = '🏳'
up_to_date = ''
untracked = ''
ahead = '⇡${count}'
diverged = '⇕⇡${ahead_count}⇣${behind_count}'
behind = '⇣${count}'
stashed = ''
modified = ''
staged = '[++\($count\)](#a9b665)'
renamed = '襁'
deleted = ''

[kubernetes]
disabled = false
format = 'via [󱃾 $context\($namespace\)](#d3869b bold) '

[docker_context]
disabled = false
format = 'via [ $context\($namespace\)](#d3869b bold) '
detect_files = ['Dockerfile', 'docker-compose.yml', 'docker-compose.yaml']

[python]
symbol = '󰌠'
format = '[//](#3c3836) [${symbol} ${pyenv_prefix}(${version} )(\($virtualenv\) )]($style) '
style = '#d8a657'

[golang]
symbol = ''
style = '#d3869b'
format = '[//](#3c3836) [${symbol} ${version}]($style) '

[c]
symbol = ''
style = '#7daea3'
format = '[//](#3c3836) [${symbol} ${version}]($style) '

[lua]
symbol = ''
style = '#b4befe'
format = '[//](#3c3836) [${symbol} ${version}]($style) '

# --------------------------------------
# OLD CONFIG COLORS MORE LIKE CATPUTINE
# --------------------------------------

# add_newline = true
# command_timeout = 2000
#
# format = """$env_var$os$username$hostname$kubernetes$docker_context$directory$git_branch$git_status$python$golang$c$lua
# $character
# """
#
# [character]
# success_symbol = "[╰⎯](white)"
# error_symbol = "[╰⎯](white)"
#
# [env_var]
# symbol = "╭╴"
# variable = 'SHELL'
# format = "$symbol"
# disabled = false
#
# [os]
# format = '[$symbol](#89b4fa) '  # Light Blue
# disabled = false
#
# [os.symbols]
# Windows = ''
# Arch = ''
# Fedora = ''
# Ubuntu = ''
# Macos = '󰀵'
# Unknown = '󰠥'
#
# [username]
# style_user = '#f2cdcd bold'  # Flamingo
# style_root = '#f38ba8 bold'  # Red
# format = '[//](white) [$user]($style) '
# disabled = false
# show_always = true
#
# [hostname]
# ssh_only = false
# format = '[//](white) [$hostname](#94e2d5 bold) '  # Teal
# disabled = false
#
# [directory]
# truncation_length = 0
# truncation_symbol = '…/'
# home_symbol = '~'
# read_only = '  '
# format = '[//](white) [$path]($style)[$read_only]($read_only_style) '
# style = '#89b4fa'  # Blue
# read_only_style = '#f38ba8'  # Red
#
# [git_branch]
# symbol = ' '
# format = '[//](white) [$symbol\[$branch\]]($style) '
# style = '#a6e3a1'  # Green
#
# [git_status]
# disabled = true
# format = '[ $all_status $ahead_behind]($style) '
# style = '#a6e3a1'  # Green
# conflicted = '🏳'
# up_to_date = ''
# untracked = ''
# ahead = '⇡${count}'
# diverged = '⇕⇡${ahead_count}⇣${behind_count}'
# behind = '⇣${count}'
# stashed = ''
# modified = ''
# staged = '[++\($count\)](green)'
# renamed = '襁'
# deleted = ''
#
# [kubernetes]
# disabled = false
# format = 'via [󱃾 $context\($namespace\)](#f2cdcd bold) '  # Flamingo
#
# [docker_context]
# disabled = false
# format = 'via [ $context\($namespace\)](#f2cdcd bold) '  # Flamingo
# detect_files = ['Dockerfile', 'docker-compose.yml', 'docker-compose.yaml']
#
# [python]
# symbol = '󰌠'
# python_binary = ['./venv/bin/python', 'python', 'python3', 'python2']
# format = '[//](white) [${symbol} ${pyenv_prefix}(${version} )(\($virtualenv\) )]($style) '
# style = '#f9e2af'  # Yellow
#
# [golang]
# symbol = ''
# style = '#cba6f7'  # Purple
# format = '[//](white) [${symbol} ${version}]($style) '
# disabled = false
#
# [c]
# symbol = ''
# style = '#74c7ec'  # Saphire
# format = '[//](white) [${symbol} ${version}]($style) '
#
# [lua]
# symbol = ''
# style = '#b4befe'  # Rosewater
# format = '[//](white) [${symbol} ${version}]($style) '
