-- Generated by hyprmoncfg

hl.monitor({
  output = "desc:LG Electronics LG ULTRAGEAR+ 306NTABA9664",
  mode = "2560x1440@59.95",
  position = "1920x0",
  scale = 1,
  sdr_min_luminance = 0.2,
  sdr_max_luminance = 80,
})

hl.monitor({
  output = "desc:AU Optronics 0x208D",
  disabled = true,
})

hl.workspace_rule({ workspace = "1", monitor = "desc:LG Electronics LG ULTRAGEAR+ 306NTABA9664", default = true, persistent = true })
hl.workspace_rule({ workspace = "2", monitor = "desc:LG Electronics LG ULTRAGEAR+ 306NTABA9664", persistent = true })
hl.workspace_rule({ workspace = "3", monitor = "desc:LG Electronics LG ULTRAGEAR+ 306NTABA9664", persistent = true })
hl.workspace_rule({ workspace = "4", monitor = "desc:LG Electronics LG ULTRAGEAR+ 306NTABA9664", persistent = true })
hl.workspace_rule({ workspace = "5", monitor = "desc:LG Electronics LG ULTRAGEAR+ 306NTABA9664", persistent = true })
