-- Generated by hyprmoncfg

hl.monitor({
  output = "desc:AU Optronics 0x208D",
  mode = "1920x1080@60.05",
  position = "0x600",
  scale = 1,
  sdr_min_luminance = 0.2,
  sdr_max_luminance = 100,
})

hl.workspace_rule({ workspace = "1", monitor = "desc:AU Optronics 0x208D", default = true, persistent = true })
hl.workspace_rule({ workspace = "2", monitor = "desc:AU Optronics 0x208D", persistent = true })
hl.workspace_rule({ workspace = "3", monitor = "desc:AU Optronics 0x208D", persistent = true })
hl.workspace_rule({ workspace = "4", monitor = "desc:AU Optronics 0x208D", persistent = true })
hl.workspace_rule({ workspace = "5", monitor = "desc:AU Optronics 0x208D", persistent = true })
